// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SociedadFomento.Infrastructure.Persistence;

#nullable disable

namespace SociedadFomento.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SociedadFomentoDbContext))]
    [Migration("20260927234601_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SociedadFomento.Domain.Entities.AccountingEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasFilter("[PaymentId] IS NOT NULL");

                    b.HasIndex("EntryDate", "Type", "Status");

                    b.ToTable("AccountingEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountingEntries_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_AccountingEntries_Cancellation", "([Status] = 1 AND [CancelledAtUtc] IS NULL) OR ([Status] = 2 AND [CancelledAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_AccountingEntries_Source", "([Source] = 1 AND [Type] = 1 AND [PaymentId] IS NOT NULL) OR ([Source] = 2 AND [PaymentId] IS NULL)");

                            t.HasCheckConstraint("CK_AccountingEntries_Type", "[Type] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.FeeObligation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FeeRateId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<long>("MembershipPeriodId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("FeeRateId");

                    b.HasIndex("MembershipPeriodId");

                    b.HasIndex("Period");

                    b.HasIndex("MemberId", "Period")
                        .IsUnique();

                    b.ToTable("FeeObligations", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeeObligations_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_FeeObligations_Period", "DAY([Period]) = 1");
                        });
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.FeeRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EffectiveMonth")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveMonth")
                        .IsUnique();

                    b.ToTable("FeeRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeeRates_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_FeeRates_EffectiveMonth", "DAY([EffectiveMonth]) = 1");
                        });
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Members", null, t =>
                        {
                            t.HasCheckConstraint("CK_Members_Address_NotEmpty", "LEN([Address]) > 0");

                            t.HasCheckConstraint("CK_Members_Dni_NotEmpty", "LEN([Dni]) > 0");

                            t.HasCheckConstraint("CK_Members_FirstName_NotEmpty", "LEN([FirstName]) > 0");

                            t.HasCheckConstraint("CK_Members_LastName_NotEmpty", "LEN([LastName]) > 0");

                            t.HasCheckConstraint("CK_Members_Phone_NotEmpty", "LEN([Phone]) > 0");

                            t.HasCheckConstraint("CK_Members_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.MembershipPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasFilter("[EndDate] IS NULL");

                    b.HasIndex("MemberId", "StartDate");

                    b.ToTable("MembershipPeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_MembershipPeriods_Dates", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Method")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "PaymentDate");

                    b.HasIndex("PaymentDate", "Method");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_Cancellation", "([Status] = 1 AND [CancelledAtUtc] IS NULL) OR ([Status] = 2 AND [CancelledAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Payments_Method", "[Method] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.PaymentAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FeeObligationId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FeeObligationId")
                        .IsUnique()
                        .HasFilter("[ReleasedAtUtc] IS NULL");

                    b.HasIndex("PaymentId", "FeeObligationId")
                        .IsUnique();

                    b.ToTable("PaymentAllocations", (string)null);
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.AccountingEntry", b =>
                {
                    b.HasOne("SociedadFomento.Domain.Entities.Payment", "Payment")
                        .WithOne("AccountingEntry")
                        .HasForeignKey("SociedadFomento.Domain.Entities.AccountingEntry", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.FeeObligation", b =>
                {
                    b.HasOne("SociedadFomento.Domain.Entities.FeeRate", "FeeRate")
                        .WithMany("FeeObligations")
                        .HasForeignKey("FeeRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SociedadFomento.Domain.Entities.Member", "Member")
                        .WithMany("FeeObligations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SociedadFomento.Domain.Entities.MembershipPeriod", "MembershipPeriod")
                        .WithMany("FeeObligations")
                        .HasForeignKey("MembershipPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeRate");

                    b.Navigation("Member");

                    b.Navigation("MembershipPeriod");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.MembershipPeriod", b =>
                {
                    b.HasOne("SociedadFomento.Domain.Entities.Member", "Member")
                        .WithMany("MembershipPeriods")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SociedadFomento.Domain.Entities.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("SociedadFomento.Domain.Entities.FeeObligation", "FeeObligation")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("FeeObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SociedadFomento.Domain.Entities.Payment", "Payment")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeObligation");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.FeeObligation", b =>
                {
                    b.Navigation("PaymentAllocations");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.FeeRate", b =>
                {
                    b.Navigation("FeeObligations");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.Member", b =>
                {
                    b.Navigation("FeeObligations");

                    b.Navigation("MembershipPeriods");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.MembershipPeriod", b =>
                {
                    b.Navigation("FeeObligations");
                });

            modelBuilder.Entity("SociedadFomento.Domain.Entities.Payment", b =>
                {
                    b.Navigation("AccountingEntry");

                    b.Navigation("PaymentAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
